#!/usr/bin/env node
/**
 * generate-sitemap.mjs — zero-dep build-time sitemap generator (F8)
 *
 * Reads route slugs straight out of the TS data modules (regex source scan,
 * no TS toolchain needed) and writes public/sitemap.xml with absolute URLs.
 *
 * Sources:
 *   - src/data/insights.ts  → INSIGHT_ARTICLES keys (站內長文 only;AIHOT
 *     外部情報無站內詳情頁,不收錄)
 *   - src/data/cases.ts     → cases[] slugs
 *   - src/data/experts.ts   → experts[] slugs where verified: true
 *
 * Run: npm run sitemap
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const BASE = "https://aigro-blue.vercel.app";

const read = (rel) => readFileSync(join(ROOT, rel), "utf8");

/**
 * Slice out a top-level `export const NAME ... = <opener> ... <closer>;` block.
 * v1.27:mock 數據移除後 INSIGHT_ARTICLES / cases 已唔存在 — export 缺席時
 * 回空字串(零 slug),唔再 throw,等 sitemap 只收真實 routes。
 */
function block(src, name, opener, closer) {
  const start = src.indexOf(`export const ${name}`);
  if (start === -1) return "";
  const openIdx = src.indexOf(opener, start);
  const endIdx = src.indexOf(`\n${closer};`, openIdx);
  if (openIdx === -1 || endIdx === -1)
    throw new Error(`block for ${name} not terminated`);
  return src.slice(openIdx, endIdx);
}

// --- 靜態 routes（與 App.tsx 公開路由同步） ---
const STATIC_ROUTES = [
  { path: "/", changefreq: "daily", priority: "1.0" },
  { path: "/insights", changefreq: "hourly", priority: "0.9" },
  { path: "/insights/daily", changefreq: "daily", priority: "0.9" },
  { path: "/cases", changefreq: "weekly", priority: "0.8" },
  { path: "/experts", changefreq: "weekly", priority: "0.8" },
  { path: "/ask", changefreq: "monthly", priority: "0.6" },
  { path: "/pricing", changefreq: "monthly", priority: "0.7" },
  { path: "/developers", changefreq: "weekly", priority: "0.8" },
  { path: "/skills", changefreq: "weekly", priority: "0.7" },
  { path: "/branding", changefreq: "monthly", priority: "0.6" },
  { path: "/guides/100x-ai-growth-marketer", changefreq: "monthly", priority: "0.7" },
  { path: "/data", changefreq: "monthly", priority: "0.6" },
  { path: "/access", changefreq: "monthly", priority: "0.5" },
  { path: "/join", changefreq: "monthly", priority: "0.6" },
  { path: "/login", changefreq: "monthly", priority: "0.4" },
];

// --- insights:INSIGHT_ARTICLES keys(站內長文,非 AIHOT) ---
const insightsSrc = read("src/data/insights.ts");
const articlesBlock = block(insightsSrc, "INSIGHT_ARTICLES", "{", "}");
const articleSlugs = [
  ...articlesBlock.matchAll(/^ {2}"([^"]+)": \{/gm),
].map((m) => m[1]);

// --- cases:所有案例 slug ---
const casesSrc = read("src/data/cases.ts");
const casesBlock = block(casesSrc, "cases", "[", "]");
const caseSlugs = [...casesBlock.matchAll(/slug: "([^"]+)"/g)].map((m) => m[1]);

// --- experts:僅 verified(草稿席不出 sitemap) ---
const expertsSrc = read("src/data/experts.ts");
const expertsBlock = block(expertsSrc, "experts", "[", "]");
const expertSlugs = [
  ...expertsBlock.matchAll(/slug: "([^"]+)"[\s\S]*?verified: (true|false)/g),
]
  .filter((m) => m[2] === "true")
  .map((m) => m[1]);

const urls = [
  ...STATIC_ROUTES.map((r) => ({ loc: r.path, ...r })),
  ...articleSlugs.map((s) => ({
    loc: `/insights/${s}`,
    changefreq: "monthly",
    priority: "0.7",
  })),
  ...caseSlugs.map((s) => ({
    loc: `/cases/${s}`,
    changefreq: "monthly",
    priority: "0.7",
  })),
  ...expertSlugs.map((s) => ({
    loc: `/experts/${s}`,
    changefreq: "weekly",
    priority: "0.8",
  })),
];

// dedupe 保險
const seen = new Set();
const unique = urls.filter((u) => !seen.has(u.loc) && seen.add(u.loc));

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — 勿手改,改完 data 跑 npm run sitemap -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${unique
  .map(
    (u) =>
      `  <url><loc>${BASE}${u.loc}</loc><changefreq>${u.changefreq}</changefreq><priority>${u.priority}</priority></url>`
  )
  .join("\n")}
</urlset>
`;

writeFileSync(join(ROOT, "public/sitemap.xml"), xml);
console.log(
  `sitemap.xml: ${unique.length} URLs (${STATIC_ROUTES.length} static, ${articleSlugs.length} insights, ${caseSlugs.length} cases, ${expertSlugs.length} experts)`
);
